name: Faleproxy CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      id: run_tests
      run: npm run test:ci
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ github.sha }}-${{ github.run_attempt }}-${{ github.run_number }}
        path: coverage/
        retention-days: 5

  preview:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.ref != 'refs/heads/main' &&
      (github.event_name == 'push' || github.event_name == 'pull_request')
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci

    - name: Deploy to Vercel Preview
      id: deploy
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        PREVIEW_URL=$(npx vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --yes)
        echo "url=$PREVIEW_URL" >> $GITHUB_OUTPUT
        echo "Preview URL: $PREVIEW_URL"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      success()
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    concurrency: 
      group: production
      cancel-in-progress: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci

    - name: Verify tests pass
      run: npm run test:ci

    - name: Deploy to Vercel Production
      id: deploy
      if: success()
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        PROD_URL=$(npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes)
        echo "url=$PROD_URL" >> $GITHUB_OUTPUT
        echo "Production URL: $PROD_URL"
