name: Faleproxy CI

on:
  # Only trigger on main branch events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      id: run_tests
      run: npm run test:ci
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ github.sha }}-${{ github.run_attempt }}-${{ github.run_number }}
        path: coverage/
        retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # Only deploy on main branch pushes when tests pass
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      success()
    environment: production
    # Ensure only one deployment runs at a time
    concurrency: 
      group: production
      cancel-in-progress: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci

    # Double-check tests before deployment
    - name: Verify tests pass
      run: npm run test:ci

    - name: Deploy to Vercel Production
      if: success() # Only deploy if the verification tests passed
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
